set -a terminal-features "tmux-256color:RGB"
set -g prefix C-s
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g mouse on
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=blue bold"

set -g automatic-rename off
set -g allow-rename off

set -g status-interval 5

#set -g status-left "#S "

set -g status-right '#[fg=green]#(git -C "#{pane_current_path}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")#[default] #[fg=white]#{?client_prefix,_ ,}#(timew | awk "/^ *Total/ {print \$NF}") #[bg=green,fg=black,bold]#(timew | awk "/^ *Tracking/ {print \" \" \$NF \" \"}")#[bg=default]'

bind r source-file "~/.config/tmux/tmux.conf"   # reload config
bind b set -g status                            # toggle status bar
bind-key -n M-BSpace send-keys C-w             # delete previous word

bind f run "tmux neww ~/.config/scripts/tmux-session-dispensary.sh"
bind g run "~/.config/scripts/open-github.sh"
bind t run "tmux neww ~/.config/scripts/time.sh"
bind N run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/notes"
bind P run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/projects"
bind D run "~/.config/scripts/tmux-session-dispensary.sh ~/.config"
bind H run "~/.config/scripts/tmux-session-dispensary.sh ~"
bind S run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/projects/stormy"
bind G neww -n "git" -S lazygit
bind o neww -S -n "BOOK" "nvim -R ~/bookmarks.csv"

set -g mode-keys vi

bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "pbcopy"
